const ANALYSIS_TYPES = {
  EDA: "EDA",
  STATISTICAL: "STATISTICAL",
  MACHINE_LEARNING: "MACHINE_LEARNING",
  INSIGHT: "INSIGHT",
};

const ANALYSIS_JOB_STATUS = {
  PENDING: "PENDING",
  RUNNING: "RUNNING",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
};

export {
  ANALYSIS_TYPES,
  ANALYSIS_JOB_STATUS,
};