const ANALYSIS_STATE = {
  IDLE: "IDLE",
  STARTING: "STARTING",
  RUNNING: "RUNNING",
  COMPLETED: "COMPLETED",
  RESULT_READY: "RESULT_READY",
  FAILED: "FAILED",
  TIMEOUT: "TIMEOUT",
};

export { ANALYSIS_STATE };